### ISSUE TITLE
Provide example

### ISSUE THREAD

**Issue by amitaibu** [axel-angel/yesod-auth-token#1]
Is there an example of how to use this with a scaffolded yesod project?

**Comment by axel-angel** [comment]
You need to create an instance `YesodAuthLdap` for your `App` in your Foundation:

```haskell
instance YesodAuthLdap App where
    getLdapConfig = do
        extra <- getExtra
        return LDAPConfig
            { usernameFilter = \n -> "mail=" <> n
            , identifierModifier = \n _ -> n
            , ldapUri = unpack $ appLdapUri extra
            , baseDN = Just $ unpack $ appLdapDN extra
            , initDN = unpack $ appLdapAuthDN extra
            , initPass = unpack $ appLdapAuthPass extra
            , ldapScope = LdapScopeSubtree
            }
```

Here I used information from the config. Does it help? If so I'll put that into the README.

**Comment by axel-angel** [comment]
Then in your `YesodAuth` you can do something like this:

```haskell
instance YesodAuth App where
 -- …
     authenticate (Creds "LDAP" ident extra) = runDB $ do
        x <- getBy $ UniqueUser $ strip ident
        uid <- case x of
            Just (Entity uid _) ->
                return uid
            Nothing -> do
                insert $ (userDefault ident)
                    { userName = fullname
                    , userVerified = True
                    , userIsAdmin = uAdmin
                    , userIsLocked = not uEnable
                    }

        return $ Authenticated uid
```

**Comment by amitaibu** [comment]
I was actually thinking of managing my own tokens, so no lap is needed.

My idea is to have a token table that holds the random token,  uid and timestamp.

So I thought this repo can do some of the heavy lifting. Am I on the right track? :)

**Comment by axel-angel** [comment]
I don't understand "your own tokens", what tokens are you talking about?

If you mean the uuid, then you can customize the way the path to the auth entity is formed from the data you have at login.

**Comment by axel-angel** [comment]
Ah mhh… sorry I misread the project name, it's not the ldap here, sorry :) Let me come with the correct examples then.

**Comment by axel-angel** [comment]
I deleted my answers above because they were related to my other project for ldap. Sorry for the noise. I've updated the README with an example of what to can add in your Foundation. This should finally answer your question :)

https://github.com/axel-angel/yesod-auth-token

PS: thanks to you, both of my two yesod projects are documented with a README :+1: I was being a bit lazy.

**Comment by amitaibu** [comment]
Thanks, I'll check the README :)
