### ISSUE TITLE
How to add package to project

### ISSUE THREAD

**Issue by amitaibu** [axel-angel/yesod-auth-token#2]
Sorry for the newbie question, but it seems that adding `yesod-auth-token` in my cabal file and running `stack build` or `stack solver --update-config` isn't enough.

**Comment by axel-angel** [comment]
If you have a sandbox, you need to add this package:

```
cabal sandbox add-source path-to-repo
```

**Comment by amitaibu** [comment]
Thanks. btw, are you planning on adding it to hackage?

**Comment by amitaibu** [comment]
1. I have cloned the repo in the root of my project
2. I've `rm -rf yesod-auth-token/.git`
3. `cabal sandbox add-source yesod-auth-token`

But then I get the error:

```
cabal sandbox add-source yesod-auth-token
cabal: The package environment file
'/Library/WebServer/Documents/haskell/yesod-hedley/cabal.sandbox.config'
doesn't exist
```

Is there a `stack` way to add it?

**Comment by axel-angel** [comment]
This command works if you have a cabal sandbox, that's the usual way I install dependency for my projects. If you aren't working with sandboxes, one thing you could do is just `cabal install` which will register the package globally.

I could try to add my packages on cabal and see. Never done it before so I'm not sure how much work is needed.

PS: why do you remove the .git ?

**Comment by amitaibu** [comment]
I see that I can add it in my `stack.yaml` under `packages`, e.g.:

``` yaml
flags: {}
extra-package-dbs: []
packages:
- '.'
- 'yesod-auth-token'
```

however, when I `stack build` I get:

```
--  Failure when adding dependencies:    
      persistent: needed (>=1.2 && <2.1), 2.2.4 found (latest applicable is 2.0.8)
      yesod-core: needed (>=1.2 && <1.3), 1.4.18.1 found (latest applicable is 1.2.20.1)
      yesod-form: needed (>=1.3 && <1.4), 1.4.6 found (latest applicable is 1.3.16)
    needed for package yesod-auth-token-0.1
```

So, maybe yesod-auth-token's dependencies should be less strict?

**Comment by axel-angel** [comment]
Depends if it works with these versions. Try relaxing them in its cabal file and if everything works fine then I can update them here. O/w if it breaks, you may need to adapt a bit the code to accommodate the new versions.

**Comment by amitaibu** [comment]
hmm, also after removing the package restrictions, there's an error:

```
    /Library/WebServer/Documents/haskell/yesod-hedley/Foundation.hs:7:8:
        Could not find module ‘Yesod.Auth.Token’
        Perhaps you meant Yesod.Auth.Routes
```

I tried adding `hs-source-dirs: Yesod`, but didn't do it. I hope I'll find the problem and be able to provide a PR :)

**Comment by axel-angel** [comment]
Can you try this fork https://github.com/sajith/yesod-auth-token ? It seems @sajith added some stuff related to stack. Is it working for you? If it does, I will merge it here.

**Comment by amitaibu** [comment]
I got it to work - so I'll create a PR. I'll check that other repo as-well

**Comment by ghost** [comment]
Merged your PR and updated the README. Everything should work, re-open the issue if  something I did breaks your stuff (my tests work fine.)
